### ISSUE TITLE
Использование GitHub Pages

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/practice-2020-3d-molecula#10]
Поскольку у вас статический сайт, для него можно включить GitHub Pages.

> Напомню, GitHub Pages — это создание статического сайта по адресу `〈username〉.github.io/〈reponame〉` для репозитория `github.com/〈username〉/〈reponame〉`, сайт строится из содержимого репозитория, при этом файлы Markdown преобразуются в HTML. Главной страницей отображается или `index.html` (если есть), или `README.md`.

Так что GitHub Pages я вам включил:
<https://bmstu-iu9.github.io/practice-2020-3d-molecula/>

Теперь, чтобы на сайте показывался визуализатор, а не `README.md`, нужно `window.html` переименовать в `index.html`.

Я не включал GitHub Pages ранее, поскольку не знал, будет ли у вас сайт статическим или с серверной частью.

**Comment by SalemDrk** [comment]
Сделано

**Comment by Mazdaywik** [comment]
Замечательно! Всё работает.
