### ISSUE TITLE
Не показывает диметиловый эфир

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/practice-2020-3d-molecula#12]
Я хочу увидеть молекулу [диметилового эфира](https://ru.wikipedia.org/wiki/Диметиловый_эфир), но вместо этого вижу молекулу его изомера — этилового спирта.

![image](https://user-images.githubusercontent.com/1309859/89899839-86960e80-dbeb-11ea-9060-105383ceb88c.png)

Почему так получается?
* Я ввожу формулу неправильно.
* Проблема на стороне сервера, который по формулам даёт модели молекул.
* Проблема на вашей стороне.

**Comment by NotThatWay** [comment]
У одной и той же молекулярной формулы есть множество изомеров (для некоторых формул PubChem может представить более тысячи вариантов). Обрабатывать такое количество достаточно сложно, поэтому наше приложение выбирает тот вариант, который PubChem предоставляет первым из списка (у него это еще называется best match).
Такой вариант работы приложения мы обговаривали с нашим руководителем (Александром Вячеславовичем @alex-qrcs).

**Comment by Mazdaywik** [comment]
Ясно. Значит, так и должно быть.
