### ISSUE TITLE
Слишком тяжёлый репозиторий

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/practice-2020-3d-molecula#7]
Проблема
=======
Репозиторий неоправданно тяжёлый:
```
Z:\>time /t && git clone https://github.com/bmstu-iu9/practice-2020-3d-molecula && time /t
19:01
Cloning into 'practice-2020-3d-molecula'...
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (92/92), done.
Rremote: Total 4623 (delta 76), reused 79 (delta 38), pack-reused 4491
Receiving objects: 100% (4623/4623), 239.90 MiB | 383.00 KiB/s, done.
Resolving deltas: 100% (1333/1333), done.
Updating files: 100% (4090/4090), done.
19:12
```
Он весит 240 Мбайт и скачивался на моей машине 11 минут.

Вопрос: что же вы написали такого за месяц практики, что он весит 240 Мбайт?

Ответ: вы зачем-то добавили в репозиторий все исходники библиотеки Three.js. Зачем? Вы всё равно пользуетесь только файлом `build/three.js`, который можно просто скачать с официального сайта (<https://threejs.org/build/three.js>).

Но если уж вам хочется зачем-то иметь при себе все исходники Three.js, то можете вместо закоммичивания их всех использовать [подмодули](https://git-scm.com/book/ru/v2/Инструменты-Git-Подмодули). Хотя я не представляю, зачем они вам в проекте.

Перезапись истории
==============
Я не зачту проект, если репозиторий останется таким же тяжёлым, поэтому исходники `Tree.js` нужно будет из него удалить.

Простое удаление файлов просто создаст новый коммит, в котором эти файлы удалены. Но в истории они всё равно останутся. Поэтому вам придётся осваивать опасную команду `git filter-branch` для удаления лишних файлов из истории.

Но осваивайте `git filter-branch` уже сами. Сами всё напортачили (коммит a9073d233e503279bfdf7c9712dee7e3de0d8772 создал @Ga1ath, пулл-реквест #5 с этим коммитом открыла @CrowleyHell, одобрил его @NotThatWay), сами разбирайтесь.

Создайте новую ветку `new-master`, в истории которой то же дерево коммитов, но с удалённой подпапкой `three.js-master` (кроме файла `three.js-master/build/three.js`) и напишите мне. Я перекину ветку `master` на `new-master`. (Ветка `master` защищённая, переписывать её историю могут только админы, поэтому создавайте `new-master`).

**Comment by SalemDrk** [comment]
Вас поняли, исправим.

**Comment by Ga1ath** [comment]
Сделано (с помощью filter-branch, разумеется), размер ветки new-master составляет вменяемые 1.3 МБ.
Ветка new-master готова стать masterом)

**Comment by Mazdaywik** [comment]
Зафорспушил `master`. **Также зафорспушил `openGLbranch`.** Теперь репозиторий скачивается мгновенно и весит 278 Кбайт:
```
D:\…>git clone https://github.com/bmstu-iu9/practice-2020-3d-molecula
Cloning into 'practice-2020-3d-molecula'...
remote: Enumerating objects: 158, done.
remote: Counting objects: 100% (158/158), done.
remote: Compressing objects: 100% (73/73), done.
Receiving obj 186 (delta 89), reused 149 (delta 83), pack-reused 28
Receiving objects: 100% (186/186), 278.27 KiB | 975.00 KiB/s, done.
Resolving deltas: 100% (103/103), done.
```
