### ISSUE TITLE
Не удалось запустить по инструкции

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/practice-2020-3d-molecula#8]
Запускаю по инструкции из `README.md`:
```
Z:\practice-2020-3d-molecula>xdg-open window.html
"xdg-open" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

Z:\practice-2020-3d-molecula>
```
А в инструкции не написано, что надо установить, чтобы команда `xdg-open` работала.

----------------------

Открыл в браузере:
![image](https://user-images.githubusercontent.com/1309859/89808444-cead2680-db42-11ea-89ae-58a0d5450002.png)

В инструкции написано — введите в окно молекулу. Я ввёл `H2O`, нажал `Search` — чёрный экран (как на скриншоте). Я ввёл неправильную молекулу?

Напишите, пожалуйста, в `README.md` примеры молекул, на которые можно посмотреть.

**Comment by SalemDrk** [comment]
Молекулу можно выбирать любую, для визуализации нужно выбрать режим одной из кнопок. Об этом говорится в оповещении "ready for mode selection"

**Comment by SalemDrk** [comment]
*Одной из четырех кнопок сверху. Нижние пока не задействованы. Допишу более подробную инструкцию.

**Comment by Mazdaywik** [comment]
Комментарии можно редактировать. Для этого надо нажать на три точки рядом со смайликом.

Загрузить молекулу мне удалось, и удалось её повращать:
![image](https://user-images.githubusercontent.com/1309859/89809651-8858c700-db44-11ea-81d0-06affca238e0.png)
Кнопки Z…B вращают молекулу относительно наблюдателя, а хотелось бы вращать молекулу относительно центра масс. Но это уже другая задача #9.

По этой задаче я бы предложил молекулу отрисовывать сразу в каком-нибудь режиме по умолчанию (например, самом первом). А ещё лучше четыре кнопки заменить на радиокнопки.

**Comment by Ga1ath** [comment]
В проекте существует две возможности вращать - камеру по всем трем осям по кнопкам (в README описано), а также саму молекулу с помощью мышки (тут по двум осям, в плоскости перемещения мышки)
Также весьма полезна будет возможность приближения/отдаления молекулы (технически подъезжает/отъезжает камера, управление ее перемещением также реализовано, все описано в README)

Базовый режим отрисовки добавлен - Ball-And-Stick, а также обычные кнопки заменены на радиокнопки, как Вы предлагали

**Comment by Mazdaywik** [comment]
В обновлённом `README.md` теперь всё описано.
