### ISSUE TITLE
Неинтуитивное вращение вокруг осей

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/practice-2020-3d-molecula#9]
Кнопки `Z`…`N` действительно вращают вокруг осей. Но вращают они относительно осей наблюдателя, а не молекулу. Т.е. когда я нажимаю `C`, молекула уходит вправо, оказывается за моей спиной, появляется слева.

И это несколько странно. Хотелось бы вращать саму молекулу, чтобы видеть её с разных сторон.

**Comment by Ga1ath** [comment]
Вращение молекулы с помощью мышки реализовано и упомянуто в README

**Comment by Mazdaywik** [comment]
Значит, я проглядел.
